language: python
sudo: required
services:
- postgresql
python:
  - 3.5
  - 3.6
env:
  - DJANGO_LOGS_DIR=. DB_PASSWORD=""
addons:
  chrome: stable
before_install:
  - mkdir -p logs
  - sudo apt-get -qq update
  - sudo apt-get install python3-tk
  - npm install --prefix audio_profiling/static/ chroma-js@1.2.2 enquire.js@2.1.5 wavesurfer.js@1.1.1 admin-lte@2.3.11
                                                 sinon@2.1.0 qunit-phantomjs-runner@2.3.0 underscore@1.8.3
  - sudo apt-get install -y cython libav-tools ffmpeg git libgroove-dev libpng-dev zlib1g-dev make python3-tk gettext
  - git clone https://github.com/andrewrk/waveform.git
  - cd waveform && git checkout tags/2.0.0 && make && sudo ln -s $PWD/waveform /usr/local/bin/waveform && cd ..
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo ln -s $PWD/chromedriver /usr/local/bin/chromedriver
script:
  - python manage.py test audio_profiling.tests
  - python manage.py test functional_tests
  - pyflakes .
  - mypy --config-file mypy.ini .
  - QT_QPA_PLATFORM=offscreen phantomjs audio_profiling/static/node_modules/qunit-phantomjs-runner/runner.js
                                        audio_profiling/static/test.html
