version: '2'
services:
  db:
    restart: always
    image: postgres:latest
    ports:
     - "127.0.0.1:5432:5432"
    volumes:
      - /opt/audio-gallery/pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=audiogallery
  memcached:
    restart: always
    image: memcached:latest
    ports:
      - "127.0.0.1:11211:11211"
  rabbit:
    restart: always
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "127.0.0.1:5672:5672"
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8888:8000"
    volumes: # TODO read-only
      - ./config/nginx:/etc/nginx/conf.d
      - /opt/audio-gallery/static:/opt/audio-gallery/static
      - /opt/audio-gallery/media:/opt/audio-gallery/media
    depends_on:
      - web
  worker:
    restart: always
    build: .
    env_file: .django_env
    # only one worker container is needed, because it automatically starts 2*n+1 processes (n - num of CPU cores)
    container_name: audiogallery_worker
    volumes:
      - /opt/audio-gallery/static:/opt/audio-gallery/static
      - /opt/audio-gallery/media:/opt/audio-gallery/media
      - /opt/audio-gallery/logs:/opt/audio-gallery/logs
      - .:/src/audio-gallery/source
    depends_on:
      - db
      - memcached
      - rabbit
    environment:
      - IS_WORKER=true
  web:
    restart: always
    build: .
    env_file: .django_env
    volumes: # same as worker's
      - /opt/audio-gallery/static:/opt/audio-gallery/static
      - /opt/audio-gallery/media:/opt/audio-gallery/media
      - /opt/audio-gallery/logs:/opt/audio-gallery/logs
      - .:/src/audio-gallery/source
    expose:
      - "8000"
    depends_on:
      - db
      - memcached
      - rabbit
      - worker
#    deploy:
#      restart_policy:
#        delay: 5s
#        max_attempts: 3
#        window: 90s
